### ISSUE TITLE
Create a Google doc for meeting logs

### ISSUE THREAD

**Issue by ugurdogrusoz** [sekin72/2A.Left-For-F#2]
and make sure the instructor and the TA has read access to it. Also make sure README.md has a link to it. You will update this doc as you meet.

**Comment by sekin72** [comment]
@ugurdogrusoz I wasn't sure where to put it so I have put the link in the unstable branch in the last meeting. Now it's in the readme on the main branch as you asked. Also, the file is shared by link so anyone who has the link can access to it

**Comment by ugurdogrusoz** [comment]
thanks!
