### ISSUE TITLE
Insufficient problem statement 

### ISSUE THREAD

**Issue by ugurdogrusoz** [sekin72/2A.Left-For-F#3]
Since your project is not inspired from an existing one, you should provide more details (a few more paragraphs) on it.

**Comment by ali-z-can** [comment]
@ugurdogrusoz introduction part updated

**Comment by ugurdogrusoz** [comment]
Thanks, this is good now. I do like the project theme :) This monogame library however sounds like a gaming library which you are not supposed to use. As I mention multiple times in class, you should design from scratch not obligated to use a library s enforced design. Besides it is too early to think about implementation or design. First analyze properly, then design, and finally choose an implementation language and so on!
